///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExampleTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ExampleTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("37fefd60-d354-4e41-a55f-92004fe78efb")]
    public partial class ExampleTestRepository : RepoGenBaseFolder
    {
        static ExampleTestRepository instance = new ExampleTestRepository();
        ExampleTestRepositoryFolders.OficjalnaStronaPrezydentaRzeczypospolAppFolder _oficjalnastronaprezydentarzeczypospol;

        /// <summary>
        /// Gets the singleton class instance representing the ExampleTestRepository element repository.
        /// </summary>
        [RepositoryFolder("37fefd60-d354-4e41-a55f-92004fe78efb")]
        public static ExampleTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ExampleTestRepository() 
            : base("ExampleTestRepository", "/", null, 0, false, "37fefd60-d354-4e41-a55f-92004fe78efb", ".\\RepositoryImages\\ExampleTestRepository37fefd60.rximgres")
        {
            _oficjalnastronaprezydentarzeczypospol = new ExampleTestRepositoryFolders.OficjalnaStronaPrezydentaRzeczypospolAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("37fefd60-d354-4e41-a55f-92004fe78efb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The OficjalnaStronaPrezydentaRzeczypospol folder.
        /// </summary>
        [RepositoryFolder("35f4f9f2-734c-4178-b74f-acbb30245477")]
        public virtual ExampleTestRepositoryFolders.OficjalnaStronaPrezydentaRzeczypospolAppFolder OficjalnaStronaPrezydentaRzeczypospol
        {
            get { return _oficjalnastronaprezydentarzeczypospol; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class ExampleTestRepositoryFolders
    {
        /// <summary>
        /// The OficjalnaStronaPrezydentaRzeczypospolAppFolder folder.
        /// </summary>
        [RepositoryFolder("35f4f9f2-734c-4178-b74f-acbb30245477")]
        public partial class OficjalnaStronaPrezydentaRzeczypospolAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _kontaktInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _imieInfo;
            RepoItemInfo _nazwiskoInfo;
            RepoItemInfo _kontaktformularzkrajInfo;
            RepoItemInfo _miejscowoscInfo;
            RepoItemInfo _kodpocztowyInfo;
            RepoItemInfo _adresInfo;
            RepoItemInfo _trescInfo;
            RepoItemInfo _kodobrazkowyInfo;
            RepoItemInfo _zgodaInfo;
            RepoItemInfo _formInfo;

            /// <summary>
            /// Creates a new OficjalnaStronaPrezydentaRzeczypospol  folder.
            /// </summary>
            public OficjalnaStronaPrezydentaRzeczypospolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OficjalnaStronaPrezydentaRzeczypospol", "/dom[@domain='www.prezydent.pl']", parentFolder, 30000, null, false, "35f4f9f2-734c-4178-b74f-acbb30245477", "")
            {
                _kontaktInfo = new RepoItemInfo(this, "Kontakt", ".//div[#'zone1']/ul//span[@innertext='Kontakt']", 30000, null, "f4bbf457-00de-4bb0-9518-5fd8f933849f");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "7f6bfdb4-6ed9-4b90-8f6d-489a6e82bb38");
                _imieInfo = new RepoItemInfo(this, "Imie", ".//input[#'imie']", 30000, null, "f2a1260f-3aa7-47eb-8618-f0a18caedcf3");
                _nazwiskoInfo = new RepoItemInfo(this, "Nazwisko", ".//input[#'nazwisko']", 30000, null, "aebb9212-7953-4f4e-92cd-5426000bc4d0");
                _kontaktformularzkrajInfo = new RepoItemInfo(this, "KontaktFormularzKraj", ".//select[#'kontakt_formularz_kraj']", 30000, null, "1e5a76d5-4e18-48bf-b9e9-e9914a3bcbfb");
                _miejscowoscInfo = new RepoItemInfo(this, "Miejscowosc", ".//input[#'miejscowosc']", 30000, null, "23afdc26-bb5d-4417-aeb8-462075798a12");
                _kodpocztowyInfo = new RepoItemInfo(this, "KodPocztowy", ".//input[#'kod_pocztowy']", 30000, null, "373e2623-ca2b-4535-9c8b-70e11b2d9428");
                _adresInfo = new RepoItemInfo(this, "Adres", ".//input[#'adres']", 30000, null, "d764affa-f4e2-4f2d-953a-852a6e3de1c2");
                _trescInfo = new RepoItemInfo(this, "Tresc", ".//textarea[#'tresc']", 30000, null, "7a1812ab-00e2-47d5-a0ba-9b7a037c912f");
                _kodobrazkowyInfo = new RepoItemInfo(this, "KodObrazkowy", ".//input[#'kod_obrazkowy']", 30000, null, "ad146c82-fd04-4858-b70b-b47214701f0c");
                _zgodaInfo = new RepoItemInfo(this, "Zgoda", ".//input[#'zgoda']", 30000, null, "b1a81365-3021-47b1-81d4-d6e45b7ab6fc");
                _formInfo = new RepoItemInfo(this, "Form", ".//div[#'zone0']/form[@name='kontakt_form']/div[1]", 30000, null, "01675cd6-1274-472d-88c7-42f41d8fcc3e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("35f4f9f2-734c-4178-b74f-acbb30245477")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("35f4f9f2-734c-4178-b74f-acbb30245477")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Kontakt item.
            /// </summary>
            [RepositoryItem("f4bbf457-00de-4bb0-9518-5fd8f933849f")]
            public virtual Ranorex.SpanTag Kontakt
            {
                get
                {
                    return _kontaktInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kontakt item info.
            /// </summary>
            [RepositoryItemInfo("f4bbf457-00de-4bb0-9518-5fd8f933849f")]
            public virtual RepoItemInfo KontaktInfo
            {
                get
                {
                    return _kontaktInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("7f6bfdb4-6ed9-4b90-8f6d-489a6e82bb38")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("7f6bfdb4-6ed9-4b90-8f6d-489a6e82bb38")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Imie item.
            /// </summary>
            [RepositoryItem("f2a1260f-3aa7-47eb-8618-f0a18caedcf3")]
            public virtual Ranorex.InputTag Imie
            {
                get
                {
                    return _imieInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Imie item info.
            /// </summary>
            [RepositoryItemInfo("f2a1260f-3aa7-47eb-8618-f0a18caedcf3")]
            public virtual RepoItemInfo ImieInfo
            {
                get
                {
                    return _imieInfo;
                }
            }

            /// <summary>
            /// The Nazwisko item.
            /// </summary>
            [RepositoryItem("aebb9212-7953-4f4e-92cd-5426000bc4d0")]
            public virtual Ranorex.InputTag Nazwisko
            {
                get
                {
                    return _nazwiskoInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Nazwisko item info.
            /// </summary>
            [RepositoryItemInfo("aebb9212-7953-4f4e-92cd-5426000bc4d0")]
            public virtual RepoItemInfo NazwiskoInfo
            {
                get
                {
                    return _nazwiskoInfo;
                }
            }

            /// <summary>
            /// The KontaktFormularzKraj item.
            /// </summary>
            [RepositoryItem("1e5a76d5-4e18-48bf-b9e9-e9914a3bcbfb")]
            public virtual Ranorex.SelectTag KontaktFormularzKraj
            {
                get
                {
                    return _kontaktformularzkrajInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The KontaktFormularzKraj item info.
            /// </summary>
            [RepositoryItemInfo("1e5a76d5-4e18-48bf-b9e9-e9914a3bcbfb")]
            public virtual RepoItemInfo KontaktFormularzKrajInfo
            {
                get
                {
                    return _kontaktformularzkrajInfo;
                }
            }

            /// <summary>
            /// The Miejscowosc item.
            /// </summary>
            [RepositoryItem("23afdc26-bb5d-4417-aeb8-462075798a12")]
            public virtual Ranorex.InputTag Miejscowosc
            {
                get
                {
                    return _miejscowoscInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Miejscowosc item info.
            /// </summary>
            [RepositoryItemInfo("23afdc26-bb5d-4417-aeb8-462075798a12")]
            public virtual RepoItemInfo MiejscowoscInfo
            {
                get
                {
                    return _miejscowoscInfo;
                }
            }

            /// <summary>
            /// The KodPocztowy item.
            /// </summary>
            [RepositoryItem("373e2623-ca2b-4535-9c8b-70e11b2d9428")]
            public virtual Ranorex.InputTag KodPocztowy
            {
                get
                {
                    return _kodpocztowyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The KodPocztowy item info.
            /// </summary>
            [RepositoryItemInfo("373e2623-ca2b-4535-9c8b-70e11b2d9428")]
            public virtual RepoItemInfo KodPocztowyInfo
            {
                get
                {
                    return _kodpocztowyInfo;
                }
            }

            /// <summary>
            /// The Adres item.
            /// </summary>
            [RepositoryItem("d764affa-f4e2-4f2d-953a-852a6e3de1c2")]
            public virtual Ranorex.InputTag Adres
            {
                get
                {
                    return _adresInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Adres item info.
            /// </summary>
            [RepositoryItemInfo("d764affa-f4e2-4f2d-953a-852a6e3de1c2")]
            public virtual RepoItemInfo AdresInfo
            {
                get
                {
                    return _adresInfo;
                }
            }

            /// <summary>
            /// The Tresc item.
            /// </summary>
            [RepositoryItem("7a1812ab-00e2-47d5-a0ba-9b7a037c912f")]
            public virtual Ranorex.TextAreaTag Tresc
            {
                get
                {
                    return _trescInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Tresc item info.
            /// </summary>
            [RepositoryItemInfo("7a1812ab-00e2-47d5-a0ba-9b7a037c912f")]
            public virtual RepoItemInfo TrescInfo
            {
                get
                {
                    return _trescInfo;
                }
            }

            /// <summary>
            /// The KodObrazkowy item.
            /// </summary>
            [RepositoryItem("ad146c82-fd04-4858-b70b-b47214701f0c")]
            public virtual Ranorex.InputTag KodObrazkowy
            {
                get
                {
                    return _kodobrazkowyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The KodObrazkowy item info.
            /// </summary>
            [RepositoryItemInfo("ad146c82-fd04-4858-b70b-b47214701f0c")]
            public virtual RepoItemInfo KodObrazkowyInfo
            {
                get
                {
                    return _kodobrazkowyInfo;
                }
            }

            /// <summary>
            /// The Zgoda item.
            /// </summary>
            [RepositoryItem("b1a81365-3021-47b1-81d4-d6e45b7ab6fc")]
            public virtual Ranorex.InputTag Zgoda
            {
                get
                {
                    return _zgodaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Zgoda item info.
            /// </summary>
            [RepositoryItemInfo("b1a81365-3021-47b1-81d4-d6e45b7ab6fc")]
            public virtual RepoItemInfo ZgodaInfo
            {
                get
                {
                    return _zgodaInfo;
                }
            }

            /// <summary>
            /// The Form item.
            /// </summary>
            [RepositoryItem("01675cd6-1274-472d-88c7-42f41d8fcc3e")]
            public virtual Ranorex.DivTag Form
            {
                get
                {
                    return _formInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Form item info.
            /// </summary>
            [RepositoryItemInfo("01675cd6-1274-472d-88c7-42f41d8fcc3e")]
            public virtual RepoItemInfo FormInfo
            {
                get
                {
                    return _formInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}