///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExampleTest
{
    public partial class FillUpTemplate
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SetCountry(string argument1)
        {
        	repo.OficjalnaStronaPrezydentaRzeczypospol.KontaktFormularzKraj.Click();
        	var countryOptions= repo.OficjalnaStronaPrezydentaRzeczypospol.KontaktFormularzKraj.FindDescendants<OptionTag>();
        	
        	foreach (var country in countryOptions) {
        		if(country.Label==argument1){
        			country.Select();
        		}
        	}
        }

    }
}
